### ISSUE TITLE
A crazy little thing called validation.

### ISSUE THREAD

**Issue by andreElrico** [SanderElias/ngObservableForm#2]
Sorry Sander this is not a proper GitHub feature request but I could not find any email from you.

How will validation be handled? I think it's important to somehow land where a reactive-approach would land, while omitting the insane boilerplate.

I think we will have to use the well-established abstractions FormControl, FromGroup. But what is your view. How for example could we use a [material stepper](https://material.angular.io/components/stepper/overview) with validation using ngObserableForm?

**Comment by SanderElias** [comment]
Hi Andre, 
My email address is mentioned in my ngConf talk on this subject.
Aside from that. I'm not yet doing validations, but yes, there is a plan.
A material stepper is actually a set of forms. I would have to look into it, but yes,  hooking it up should not be rocket science.

I'm going to close this for now. Feel free to reach out to me on my email, or at Twitter (@esosanderelias)
